import React from 'react';
import Product from './Product';

export const metadata = {
    title: 'Products',
    description: 'Generated by create next app',
};

const ProductsPage = () => {
    return (
        <div>
            <Product />
        </div>
    );
};

export default ProductsPage;